### ISSUE TITLE
Simplify error handling for `parse`

### ISSUE THREAD

**Issue by Gabriella439** [k0001/pipes-attoparsec#14]
Right now `parse` returns a `Maybe (Either ParsingError r)`, which makes error handling a bit difficult.  I think you can simplify this by just adding another constructor to `ParsingError`:

``` haskell
data ParsingError
    = ParsingEOF
    | ParsingError { peContexts :: [String], peMessage :: String }
```

This simplifies the type to just return `Either ParsingError r`.

If a person wants to handle the EOF case specifically, then they can just write:

``` haskell
example = do
    x <- parse parser
    case x of
        Left ParsingEOF              -> ...
        Left (ParsingError ctxs msg) -> ...
        Right r                      -> ...
```

... but by merging EOF into `ParsingError`, you make it easier for people to handle both EOF and parsing errors in a single stroke:

``` haskell
example = do
    x <- parse parser
    case x of
        Left  e -> ...
        Right r -> ...
```

**Comment by howsiwei** [comment]
I'm not convinced that this is the right approach. What if the Attoparsec parser accepts empty input (say `many anyChar`)? If we are the end of the input, using this approach returns `Nothing` but I argue that it is better to return `""`.

I suggest not to treat EOF as special case. Even if we are at the end of input, just let Attoparsec parse the empty string and return `Either ParsingError a` depending on the parse result.
